project:
  type: website

website:
  title: "Econometria no Quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      
format:
  html:
    theme: default 
    css: styles.css

editor: visual

